name: deploy-content
# This workflow deploys the content of the container package to an S3 bucket
# It triggers on pushes to the main branch, specifically for changes in the container package
# It uses the AWS CLI to sync the built content to the specified S3 bucket
# The AWS credentials are stored in GitHub secrets for security
# The workflow runs on the latest Ubuntu environment
# The working directory for the steps is set to 'packages/container'

on:
  push:
    branches:
      - main
    paths:
      - 'packages/container/**'
    
defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ""
      

